"""two

Revision ID: 50d4a9020e5e
Revises: e098c03cf138
Create Date: 2020-07-10 07:03:40.888977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50d4a9020e5e'
down_revision = 'e098c03cf138'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_index(op.f('ix_User_username'), 'User', ['username'], unique=False)
    op.create_table('Record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('pub_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Record_id'), 'Record', ['id'], unique=False)
    op.create_index(op.f('ix_Record_pub_date'), 'Record', ['pub_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Record_pub_date'), table_name='Record')
    op.drop_index(op.f('ix_Record_id'), table_name='Record')
    op.drop_table('Record')
    op.drop_index(op.f('ix_User_username'), table_name='User')
    op.drop_table('User')
    # ### end Alembic commands ###
